### ISSUE TITLE
Mixture of two or three filters sometimes causes application to crash

### ISSUE THREAD

**Issue by modrzew** [modrzew/ekoie#1]
Most probably has something to do with panzerfaust filter. I believe it crashed when the panzerfaust song was actually shorter than the filtered track.

Traceback:

``` pytb
Traceback (most recent call last):
  File "interface.py", line 359, in <module>
    app.run()
(a lot of npyscreen lines, unrelevant)
  File "interface.py", line 108, in h_play
    track = filters.apply(app.current_track, self.parentApp.filters)
  File "/home/modrzew/Projekty/ekoie/filters.py", line 141, in apply
    track = FILTERS[fil](track)
  File "/home/modrzew/Projekty/ekoie/filters.py", line 80, in panzerfaust
    return audio.mix_segments([track, panzer_track], slice_length)
  File "/home/modrzew/Projekty/ekoie/audio.py", line 165, in mix_segments
    raise ValueError('all segments need to have the same length')
ValueError: all segments need to have the same length
```

**Comment by modrzew** [comment]
Hopefully fixed in f57f3c1.
