### ISSUE TITLE
Incorrect file format - application crash

### ISSUE THREAD

**Issue by modrzew** [modrzew/ekoie#2]
One of the tracks used was probably in incorrect format, and that caused application to crash.

Ocurred during loading extra tracks (besides selected one).

Traceback:

``` pytb
Traceback (most recent call last):
  File "interface.py", line 423, in <module>
    app.run()
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/wgtitlefield.py", line 119, in edit
    self.entry_widget.edit()
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/wgmultiline.py", line 581, in edit
    self.get_and_use_key_press()
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/wgwidget.py", line 601, in get_and_use_key_press
    self.when_check_value_changed()
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/npyscreen/wgwidget.py", line 648, in when_check_value_changed
    self.parent_widget.when_value_edited()
  File "interface.py", line 103, in when_value_edited
    track = audio.load(filename)
  File "/home/modrzew/Projekty/ekoie/audio.py", line 85, in load
    return pydub.AudioSegment.from_mp3(filename)
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/pydub/audio_segment.py", line 358, in from_mp3
    return cls.from_file(file, 'mp3')
  File "/home/modrzew/.virtualenvs/ekoie/lib/python3.4/site-packages/pydub/audio_segment.py", line 345, in from_file
    raise CouldntDecodeError("Decoding failed. ffmpeg returned error code: {0}".format(retcode))
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1
```

**Comment by modrzew** [comment]
One of the tracks was in an invalid format. Not related to the code.
